### ISSUE TITLE
TODO - Enemies

### ISSUE THREAD

**Issue by Drackor15** [Drackor15/Vielen_Drache#2]
# Enemies

## Enemy Movement
- When the player is above an enemy and moves in the opposite direction that the enemy is pathing, the enemy takes a while to readjust and move in the other direction. This is because it still maintains its momentum from the previous direction it is pathing. A custom method should be created to detect when a player moves like this so that the enemy can apply twice the momentum for a small period of time (or simply kill momentum if there exists a handy method for rigid bodies).
- jumping is wonky AF. I think I'll fix this by making a **Target** variable. The Player Transform will be assigned to the Target variable and fulfill the function it accomplished before, however, whenever the enemy needs to leap it will 'search' for an appropriate block to initiate a leap from and that will become the new target. An alternative is instead of relying on math... we create designated areas in our maps where enemies can leap from one platform to another and simply move them in a curve from point a to point b.

## Enemy Animation
- Enemies need animations for their various states
- Enemies need to flip based on the direction they are pathing in

**Comment by Jhet-Birchem** [comment]
Connor has completed this.
